### ISSUE TITLE
Widgets Composition

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#26]
Make a home page widget, with two tabs:
- [x] clinical view
- [x] explainer view

**Comment by tuner** [comment]
Relevant Lit documentation: https://lit.dev/docs/composition/component-composition/

This could be similar to something like: https://www.webcomponents.org/element/HTMLElements/smart-tabs
However, I'd be careful in adding random off-the-shelf components to the project because they may suddenly add tons of dependencies. Implementing something like that by ourselves should be quite straightforward.

**Comment by jdreo** [comment]
Current target:

- [ ] patient card
- [ ] patient selector

**Comment by jdreo** [comment]
I keep it open as a reminder to review the new architecture.
