### ISSUE TITLE
Automate documentation build pipelines.

### ISSUE THREAD

**Issue by jdreo** [oncodash/oncodash#4]
- [x] for backend (Sphinx?)
- [x] for frontend (MkDocs?)
- [x] upload the built doc somewhere (demo server or readthedocs.io?)
- [x] find a way to have an index referring to both the frontend and backend pages.

**Comment by prittt** [comment]
- Documentation generation script (based on sphinx) is implemented by [this](https://github.com/oncodash/oncodash/actions/workflows/build-docs.yml) gh-action
- The documentation is automatically uploaded to the project webpage so that the repo is selfcontained: https://oncodash.github.io/oncodash/
- [This](https://github.com/oncodash/oncodash/actions/workflows/cc-changelog.yml) gh-action implements automatic changelog generation based on conventional commits
